---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tenu7190/atoopv.com/
    - export PATH="/opt/alt/alt-nodejs24/root/usr/bin:$PATH"
    - cd /home/tenu7190/astera/client
    - npm ci
    - npm run build
    - /bin/cp -R dist/. $DEPLOYPATH