---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tenu7190/public_html/
    - source /home/tenu7190/nodevenv/astera-api/24/bin/activate
    - cd /home/tenu7190/astera/client
    - npm ci
    - npm run build
    - /bin/cp -R dist/. $DEPLOYPATH