/**
 * Blog-style article data used by the homepage's offers/timeline section.
 */

export const BLOG_ARTICLES = [
  {
    id: 'a1',
    date: '2024-03-08',
    year: '2024',
    month: 'MARS',
    topic: 'Juridique',
    title: 'Les nouvelles obligations du CSE en matière de RGPD',
    excerpt: 'Ce que change la mise à jour du règlement pour la gestion des données des salariés.',
    readingTime: '5 min',
    author: 'Équipe ATOOPV',
  },
  {
    id: 'a2',
    date: '2024-09-19',
    year: '2024',
    month: 'SEPT',
    topic: 'Budget',
    title: 'Bien répartir le budget ASC en fin d’exercice',
    excerpt: 'Trois méthodes simples pour clôturer un exercice budgétaire sans mauvaise surprise.',
    readingTime: '6 min',
    author: 'Julie Marchand',
  },
  {
    id: 'a3',
    date: '2025-01-22',
    year: '2025',
    month: 'JANV',
    topic: 'Procès-verbal',
    title: 'Rédiger un procès-verbal opposable en moins de 48h',
    excerpt: "La méthode ATOOPV pour transformer une réunion en document diffusable rapidement.",
    readingTime: '4 min',
    author: 'Équipe ATOOPV',
  },
  {
    id: 'a4',
    date: '2025-05-06',
    year: '2025',
    month: 'MAI',
    topic: 'Santé au travail',
    title: 'Document unique : les erreurs les plus fréquentes',
    excerpt: 'Un tour d’horizon des oublis qui exposent employeur et CSE lors d’un contrôle.',
    readingTime: '7 min',
    author: 'Marc Dubreuil',
  },
  {
    id: 'a5',
    date: '2025-08-14',
    year: '2025',
    month: 'AOÛT',
    topic: 'Négociation',
    title: 'Préparer une NAO : la check-list en 9 points',
    excerpt: 'Chiffres, revendications, calendrier : ce qu’il faut réunir avant la première séance.',
    readingTime: '5 min',
    author: 'Équipe ATOOPV',
  },
  {
    id: 'a6',
    date: '2025-11-03',
    year: '2025',
    month: 'NOV',
    topic: 'Actualité CSE',
    title: 'Ce que la loi de finances 2026 change pour les CSE',
    excerpt: 'Les mesures qui touchent directement le fonctionnement des instances représentatives.',
    readingTime: '6 min',
    author: 'Julie Marchand',
  },
  {
    id: 'a7',
    date: '2026-02-11',
    year: '2026',
    month: 'FÉVR',
    topic: 'Formation',
    title: 'CSSCT : faut-il systématiquement former ses membres ?',
    excerpt: "Un état des lieux des obligations réelles, au-delà des idées reçues.",
    readingTime: '4 min',
    author: 'Marc Dubreuil',
  },
  {
    id: 'a8',
    date: '2026-05-27',
    year: '2026',
    month: 'MAI',
    topic: 'Juridique',
    title: 'Consultation économique : les délais à ne pas manquer',
    excerpt: 'Un rappel précis des délais légaux pour chaque type de consultation du CSE.',
    readingTime: '5 min',
    author: 'Équipe ATOOPV',
  },
  {
    id: 'a9',
    date: '2026-09-01',
    year: '2026',
    month: 'SEPT',
    topic: 'Actualité CSE',
    title: 'ATOOPV, un an après : ce que les CSE en retiennent',
    excerpt: "Retour sur douze mois d'usage, avec les élus qui ont changé leur manière de travailler.",
    readingTime: '6 min',
    author: 'Équipe ATOOPV',
  },
]
