import fs from 'node:fs'

// Slugs owned by pages that still live in the bundled markdown. Generated by
// migrate/generateLegacySlugs.js.
const list = JSON.parse(fs.readFileSync(new URL('./legacySlugs.json', import.meta.url), 'utf8'))
export const LEGACY_SLUGS = new Set(list)

// Never valid as a page slug, whatever the section.
// 'veille-juridique-cse' is a fixed route that sits in front of /atoopv/ressources/:slug.
const STRUCTURAL = ['new', 'index', 'preview', 'admin', 'api', 'veille-juridique-cse']

export const isReservedSlug = (slug) => LEGACY_SLUGS.has(slug) || STRUCTURAL.includes(slug)
